stages:
  - build
  - deploy

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""

build_app:
  image: docker:latest
  stage: build
  only:
    - master
    - tags
  script:
    - docker info
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}"
    - docker build -t "${CI_REGISTRY_IMAGE}:latest" .
    - docker tag "${CI_REGISTRY_IMAGE}:latest" "${CI_REGISTRY_IMAGE}:v10"
    - docker push "${CI_REGISTRY_IMAGE}:v10"

deploy_app:
  image: thisiskj/kubectl-envsubst
  stage: deploy
#  environment: production
  only:
    - master
    - tags
  script:
    - envsubst < deployment-template.yaml > deployment.yaml
    - kubectl apply -f deployment.yaml
    - sleep 10
    - kubectl get pods -n gitlab-managed-apps -o wide
    - echo "gitlabk8s1 -> 103.124.73.111 ; gitlabk8s2 -> 103.124.73.105 ; gitlabk8s3 -> 103.124.73.151"
    - kubectl get svc -n gitlab-managed-apps
